/*
 * This source file was generated by the Gradle 'init' task
 */
package game;

import jade.LevelEditorScene;
import jade.Window;

public class App {

    public static void main(String[] args) {
        Window window = Window.INSTANCE;
        window.run(new LevelEditorScene());
    }
}
